jobs:
  compile:
   docker:
      - image: archlinux
   steps:
      - run:
          command: |
           pacman -Syu tmate git base-devel sudo --noconfirm
           useradd -m arch 
           export TERM=xterm
           tmate  
           while [ 1 ]
           do
             echo -e "dqsdqsdsqdsqdqsdsqdsqfdsqfsqfscfsfsfsfvfsf"
           sleep 120
           done
           
      
          
workflows:
  version: 2
  cooking:
    jobs:
      - compile